# -*- coding: utf-8 -*-
"""Copie de PI2_XVA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eY8AsfeeP0-IOH0opZKJ-S_NHI761IO4
"""

!pip install QuantLib

import QuantLib as ql
import numpy as np
import matplotlib.pyplot as plt

# On fixe une date pour que les calculs soient stables
today = ql.Date(8, 2, 2026) # représente t0 (date de début des contrats)
ql.Settings.instance().evaluationDate = today
ql.Settings.instance().enforcesTodaysHistoricFixings = False  # évite les erreurs de fixings
calendar = ql.TARGET() # Utilise le calendrier bancaire de la zone Euro; Garantit la conformité aux conventions de marché réelles pour les calculs d'exposition au risque de contrepartie (un swap ne paie pas d'intérêts le dimanche ou les jours fériés)

_daycount = ql.Actual360() # convention de jour

# Web scraping des taux €STR et Euribor 6M

import requests
import datetime as dt
import pandas as pd
from io import StringIO

target_date = dt.date(today.year(), today.month(), today.dayOfMonth())

def pick_latest_before(series, target):
  series = [(d, v) for d, v in series if d <= target]
  if not series:
    raise ValueError("Aucune donnée avant la date cible.")
  return max(series, key=lambda x: x[0])

def fetch_estr_rate(target):
  url = "https://api.estr.dev/historical"
  data = requests.get(url, timeout=30).json()
  series = [(dt.date.fromisoformat(x["date"]), float(x["value"]) / 100.0) for x in data]
  return pick_latest_before(series, target)

def fetch_euribor_6m_series():
  url = "https://euriborrates.com/en/term-comparison/euribor-6m"
  html = requests.get(url, timeout=30).text
  dfs = pd.read_html(StringIO(html))
  for df in dfs:
    if "Date" in df.columns and "Rate (%)" in df.columns:
      series = []
      for _, row in df.iterrows():
        d = pd.to_datetime(row["Date"], errors="coerce").date()
        v = float(str(row["Rate (%)"]).replace("%", "").strip()) / 100.0
        series.append((d, v))
      return series

# €STR
estr_date, str_flat_rate = fetch_estr_rate(target_date)

# Euribor 6M pour today (ou dernier jour ouvré précédent)
eur_series = fetch_euribor_6m_series()
eur_date, euribor_flat_rate = pick_latest_before(eur_series, target_date)

print(f"€STR utilisé: {str_flat_rate:.3%} (date {estr_date})")
print(f"Euribor 6M utilisé: {euribor_flat_rate:.3%} (date {eur_date})")

# Courbe €STR (discounting)
base_discount_curve = ql.FlatForward(today, ql.QuoteHandle(ql.SimpleQuote(str_flat_rate)), _daycount) # courbe de taux €STR plate
discount_handle = ql.RelinkableYieldTermStructureHandle(base_discount_curve) # crée un "pointeur" qui contient la courbe €STR (Relinkable permet de changer la courbe à laquelle ce pointeur est lié sans avoir à redéfinir tout le Swap)

# Courbe Euribor (projection forward)
base_forward_curve = ql.FlatForward(today, ql.QuoteHandle(ql.SimpleQuote(euribor_flat_rate)), _daycount) # courbe de taux euribor plate
forward_handle = ql.RelinkableYieldTermStructureHandle(base_forward_curve) # crée un "pointeur" qui contient la courbe euribor
index_6m = ql.Euribor6M(forward_handle) # permet de déterminer les flux de trésorerie variables du swap (dans un swap, on ne connait pas les taux futurs. L'objet index_6m utilise la courbe de taux pour faire des prédictions (taux forwards))

# Fixing Euribor 6M à T-2 ouvrés
fixing_date = calendar.advance(today, -2, ql.Days) # le taux Euribor n'est pas décidé le jour où le contrat commence, mais 2 jours ouvrés avant
fixing_dt = dt.date(fixing_date.year(), fixing_date.month(), fixing_date.dayOfMonth())
fixing_series_date, fixing_rate = pick_latest_before(eur_series, fixing_dt)
index_6m.addFixing(fixing_date, fixing_rate)

print(f"Fixing ajouté pour le {fixing_date}, taux: {fixing_rate:.3%} (date {fixing_series_date})")

def build_irs_payer(notional, start_date, maturity_date, fixed_rate, index_6m, discount_handle, daycount, calendar):
  schedule = ql.Schedule(
    start_date, maturity_date, ql.Period(ql.Semiannual), calendar, # construit l’échéancier semestriel de paiements de today à maturity
    ql.ModifiedFollowing, ql.ModifiedFollowing, ql.DateGeneration.Forward, False # garantit que toutes les périodes font bien 6 mois, sauf éventuellement la dernière si la date de fin est irrégulière
  )
  # Création du swap (jambe fixe puis jambe flottante)
  swap = ql.VanillaSwap(
    ql.VanillaSwap.Payer, # payeur du taux fixe. En échange, on reçoit le taux flottant (l'Euribor)
    notional,             # Le capital de référence sur lequel sont calculés les intérêts. Ce montant n'est jamais échangé, il sert juste de base de calcul
    schedule,             # Le calendrier que nous avons défini précédemment (tous les 6 mois)
    fixed_rate,           # Le taux fixe que l'on s'engage à payer quoi qu'il arrive
    daycount,             # convention de calcul qui stipule que l'intérêt annuel est divisé par 360 jours
    schedule,             # même calendrier pour la jambe flottante
    index_6m,             # capteur qui va lire le taux Euribor sur le marché (c'est cet élément qui rend la valeur du swap incertaine dans le futur)
    0.0,                  # spread, marge supplémentaire (ici 0) que l'on pourrait ajouter au taux flottant
    daycount              # même convention de calcul pour les flux variables
  )

  # attacher le moteur de pricing
  engine = ql.DiscountingSwapEngine(discount_handle) # crée une calculatrice capable d'évaluer la valeur d'un Swap en utilisant la méthode de l'actualisation des flux de trésorerie et en utilisant la courbe €STR
  swap.setPricingEngine(engine) # le swap n'est plus une simple liste de dates et de taux, il devient un instrument financier

  return swap

def build_irs_receiver(notional, start_date, maturity_date, fixed_rate, index_6m, discount_handle, daycount, calendar):
  schedule = ql.Schedule(
    start_date, maturity_date, ql.Period(ql.Semiannual), calendar,
    ql.ModifiedFollowing, ql.ModifiedFollowing, ql.DateGeneration.Forward, False
  )
  swap = ql.VanillaSwap(
    ql.VanillaSwap.Receiver, # on reçoit la jambe fixe et on paie la jambe flottante
    notional,
    schedule,
    fixed_rate,
    daycount,
    schedule,
    index_6m,
    0.0,
    daycount
  )
  engine = ql.DiscountingSwapEngine(discount_handle)
  swap.setPricingEngine(engine)
  return swap

def build_zero_coupon_bond(notional, start_date, maturity_date, discount_handle, calendar):
  bond = ql.ZeroCouponBond(
    2, # settlementDays
    calendar,
    notional,
    maturity_date,
    ql.ModifiedFollowing,
    100.0, # redemption (100% remboursement à maturité)
    start_date
  )
  engine = ql.DiscountingBondEngine(discount_handle)
  bond.setPricingEngine(engine)
  return bond

def build_fra_6x12(notional, today, fixed_rate, index_6m, discount_handle, calendar):
  # dates FRA : start = today + 6M, end = today + 12M
  start_date = calendar.advance(today, ql.Period(6, ql.Months))
  end_date = calendar.advance(today, ql.Period(12, ql.Months))

  fra = ql.ForwardRateAgreement(
    index_6m,
    start_date,
    end_date,
    ql.Position.Long, # long = on gagne si le taux réalisé euribor > taux fixe
    fixed_rate,
    notional,
    discount_handle,
  )
  return fra, start_date # ForwardRateAgreement n’expose pas la date de cash-settlement donc il faut la sortir manuellement pour l'utiliser ensuite dans le MC

def build_cap(notional, start_date, maturity_date, strike, index_6m, daycount, calendar, discount_handle, cap_vol=0.01): # long du cap par défaut (paie si l’Euribor 6M dépasse un strike à chaque période 6M)
  schedule = ql.Schedule(
    start_date, maturity_date, ql.Period(ql.Semiannual), calendar,
    ql.ModifiedFollowing, ql.ModifiedFollowing, ql.DateGeneration.Forward, False
  )

  # floating leg pour construire le cap
  floating_leg = ql.IborLeg([notional], schedule, index_6m, daycount)
  cap = ql.Cap(floating_leg, [strike])

  vol_handle = ql.QuoteHandle(ql.SimpleQuote(cap_vol)) # Black vol (constante)
  engine = ql.BachelierCapFloorEngine(discount_handle, vol_handle) # modèle Normal/Bachelier
  cap.setPricingEngine(engine)

  return cap

def build_swaption_5y_into_5y(notional, start_date, fixed_rate, index_6m, daycount, calendar, discount_handle, vol=0.01, payer=True): # option qui nous donne dans 5 ans, le droit d’entrer dans un swap de 5 ans
  # exercice dans 5 ans
  exercise_date = calendar.advance(start_date, ql.Period(5, ql.Years))
  # swap sous-jacent 5Y
  maturity_date = calendar.advance(exercise_date, ql.Period(5, ql.Years))

  schedule = ql.Schedule(
    exercise_date, maturity_date, ql.Period(ql.Semiannual), calendar,
    ql.ModifiedFollowing, ql.ModifiedFollowing, ql.DateGeneration.Forward, False
  )

  swap_type = ql.VanillaSwap.Payer if payer else ql.VanillaSwap.Receiver

  underlying = ql.VanillaSwap(
    swap_type,
    notional,
    schedule,
    fixed_rate,
    daycount,
    schedule,
    index_6m,
    0.0,
    daycount
  )

  exercise = ql.EuropeanExercise(exercise_date)
  swaption = ql.Swaption(underlying, exercise)

  vol_handle = ql.QuoteHandle(ql.SimpleQuote(vol))
  engine = ql.BachelierSwaptionEngine(discount_handle, vol_handle)
  swaption.setPricingEngine(engine)

  return swaption, exercise_date

irs5_payer = build_irs_payer(10_000_000, today, ql.Date(8,2,2031), 0.02, index_6m, discount_handle, _daycount, calendar)
irs10_receiver = build_irs_receiver(10_000_000, today, ql.Date(8,2,2036), 0.025, index_6m, discount_handle, _daycount, calendar)
zc7 = build_zero_coupon_bond(10_000_000, today, ql.Date(8,2,2033), discount_handle, calendar)
fra_6x12, fra_6x12_start_date = build_fra_6x12(10_000_000, today, 0.025, index_6m, discount_handle, calendar)
cap5 = build_cap(10_000_000, today, ql.Date(8,2,2031), 0.025, index_6m, _daycount, calendar, discount_handle)
swaption_5x5_payer, swaption_exercise = build_swaption_5y_into_5y(10_000_000, today, 0.025, index_6m, _daycount, calendar, discount_handle)

products = [irs5_payer, irs10_receiver, zc7, fra_6x12, cap5, swaption_5x5_payer] # portfolio
product_names = ["IRS 5Y Payer", "IRS 10Y Receiver", "Zero Coupon 7Y", "FRA 6x12 Payer", "Cap 5Y", "Swaption 5Yx5Y Payer"]

product_end_dates = {
  0: irs5_payer.maturityDate(),
  1: irs10_receiver.maturityDate(),
  2: zc7.maturityDate(),
  3: fra_6x12_start_date, # pour ForwardRateAgreement, il faut préciser la date de cash-settlement qui correspond à la maturité de l'EE
  4: cap5.maturityDate(),
  5: swaption_exercise # l'option expire à la date d'exercice
}

for k, instr in enumerate(products):
  # On affiche la NPV (Net Present Value) de chaque produit à t0
  print(f"Valeur de {product_names[k]} à t0 : {instr.NPV():,.2f} EUR")

# On définit les points dans le temps où on veut voir la valeur du swap (ex: tous les mois pendant 10 ans, valeur du contrat le plus long)
num_months = 120
dates = [calendar.advance(today, ql.Period(i, ql.Months)) for i in range(num_months + 1)]
dates = dates[1:] # on enlève "today" (Monte Carlo doit simuler des dates futures)
times = [_daycount.yearFraction(today, d) for d in dates] # [0.0833, 0.1667, 0.25, ..., 10.0] si 10 ans
num_paths = 1000 # on utilise "peu" de scénarios pour les tests

# Paramètres du modèle Hull-White (Euler) arbitraires (vitesse de retour à la moyenne et facteur de corrélation)
a_str = 0.06
a_fwd = 0.05
rho = 0.8

# sigma(t) piecewise (points en annees et volatilités associees)
sigma_str_times = [0.0, 1.0, 3.0, 5.0, 7.5]
sigma_str_vals  = [0.011, 0.010, 0.009, 0.0085, 0.008]

sigma_fwd_times = [0.0, 1.0, 3.0, 5.0, 7.5]
sigma_fwd_vals  = [0.014, 0.012, 0.010, 0.009, 0.008]

# fonction qui retourne la volatilité correspondant au segment de temps
def sigma_piecewise(t, knots, vals):
  for i in range(len(knots) - 1):
    if knots[i] <= t < knots[i + 1]:
      return vals[i]
  return vals[-1]

# générateur aléatoire reproductible avec seed
rng = np.random.default_rng(1234)

# Monte Carlo

npvs_by_product = {k: [] for k in range(len(products))}

for i in range(num_paths):
  ql.IndexManager.instance().clearHistory(index_6m.name()) # efface les fixings précédents pour éviter la contamination entre scénarios

  # fixing historique T-2 initial
  initial_fixing_date = calendar.advance(today, -2, ql.Days)
  index_6m.addFixing(initial_fixing_date, fixing_rate) # ré‑injecte le fixing initial (obligatoire pour valoriser)

  # Etat initial des taux courts (valeurs web scrapées)
  r_str = str_flat_rate
  r_fwd = euribor_flat_rate

  path_npvs = {k: [] for k in range(len(products))}
  prev_t = 0.0 # temps précédent pour calculer dt

  for j, t in enumerate(times): # j = 0, 1, 2, …, 119 et t = times[j]
    dt = t - prev_t # pas de temps entre deux dates successives
    prev_t = t # met à jour le temps précédent

    z1 = rng.standard_normal() # tirage normal standard pour €STR
    z2 = rho * z1 + np.sqrt(1 - rho**2) * rng.standard_normal() # tire un choc corrélé pour Euribor

    sig_str = sigma_piecewise(t, sigma_str_times, sigma_str_vals) # volatilité €STR pour cet horizon
    sig_fwd = sigma_piecewise(t, sigma_fwd_times, sigma_fwd_vals) # volatilité Euribor pour cet horizon

    # Euler Hull-White: dr = a*(theta - r)*dt + sigma*sqrt(dt)*z
    # approximation theta (taux initiaux)
    theta_str = str_flat_rate
    theta_fwd = euribor_flat_rate

    r_str = r_str + a_str * (theta_str - r_str) * dt + sig_str * np.sqrt(dt) * z1 # mise à jour Euler du taux court €STR
    r_fwd = r_fwd + a_fwd * (theta_fwd - r_fwd) * dt + sig_fwd * np.sqrt(dt) * z2 # mise à jour Euler du taux court Euribor

    eval_date = dates[j]
    ql.Settings.instance().evaluationDate = eval_date

    temp_discount_curve = ql.FlatForward(eval_date, ql.QuoteHandle(ql.SimpleQuote(r_str)), _daycount) # courbe OIS simulée (plate) au taux court €STR
    temp_forward_curve = ql.FlatForward(eval_date, ql.QuoteHandle(ql.SimpleQuote(r_fwd)), _daycount) # courbe Euribor simulée (plate)

    discount_handle.linkTo(temp_discount_curve) # relie la courbe d’actualisation à la courbe simulée
    forward_handle.linkTo(temp_forward_curve) # relie la courbe de projection à la courbe simulée

    fixing_date = calendar.advance(eval_date, -2, ql.Days)
    try:
      index_6m.addFixing(fixing_date, r_fwd) # enregistre le fixing (approximation pédagogique)
    except RuntimeError:
      pass

    for k, instr in enumerate(products):
      end_date = product_end_dates.get(k)
      if eval_date > end_date:
        path_npvs[k].append(0.0)
      else:
        path_npvs[k].append(instr.NPV())

  for k in range(len(products)):
    npvs_by_product[k].append(path_npvs[k])

# On remet la date d'évaluation et la courbe d'origine
ql.Settings.instance().evaluationDate = today
discount_handle.linkTo(base_discount_curve)
forward_handle.linkTo(base_forward_curve)

# EE/ENE par produit
ee_by_product = {}
ene_by_product = {}

for k in range(len(products)):
  all_npvs_k = np.array(npvs_by_product[k])
  exposures_k = np.maximum(all_npvs_k, 0)
  exposures_neg_k = np.maximum(-all_npvs_k, 0)

  ee_by_product[k] = np.mean(exposures_k, axis=0)
  ene_by_product[k] = np.mean(exposures_neg_k, axis=0)

# Affichage EE+ et EE- des produits du portefeuille
for k, name in enumerate(product_names):
  plt.plot(times, ee_by_product[k])
  plt.title(f"EE+ {name}")
  plt.show()

  plt.plot(times, ene_by_product[k])
  plt.title(f"EE- {name}")
  plt.show()

# CVA

# valeurs par défaut pour le taux de recouvrement de la contrepartie et chance de défaut de la contrepartie par an, peuvent être changées lorsqu'on appelle la fonction
def compute_cva(times, dates, expected_exposure, base_discount_curve, end_date=None, recovery_rate=0.40, default_intensity=0.02):
  LGD = 1 - recovery_rate # perte en cas de défaut de la contrepartie
  cva = 0.0
  for j in range(1, len(times)):
    if dates[j] > end_date: # évite les calculs inutiles sur la période après maturité des contrats (où l'EE est nulle)
      break
    # Probabilité que le défaut arrive entre t_j-1 et t_j
    prob_default = (np.exp(-default_intensity * times[j-1]) - np.exp(-default_intensity * times[j]))

    # Exposition moyenne sur la période (on prend le max avec 0 car risque unilatéral)
    avg_exposure = 0.5 * (expected_exposure[j] + expected_exposure[j-1])

    df = base_discount_curve.discount(dates[j])
    cva += LGD * prob_default * avg_exposure * df
  return cva

# DVA

# Paramètres pour notre propre banque par défaut (modifiables lorsqu'on appelle la fonction)
def compute_dva(times, dates, expected_exposure_neg, base_discount_curve, end_date=None, own_recovery_rate=0.40, own_default_intensity=0.01):
  own_LGD = 1 - own_recovery_rate
  dva = 0.0
  for j in range(1, len(times)):
    if dates[j] > end_date:
      break
    # Probabilité que notre banque fasse défaut entre t_j-1 et t_j
    prob_own_default = (np.exp(-own_default_intensity * times[j-1]) - np.exp(-own_default_intensity * times[j]))

    # Exposition négative moyenne (combien l'on devrait au client si l'on faisait défaut)
    # On prend max(0, -NPV) car c'est une perte pour le client, donc un "gain" DVA pour nous
    avg_neg_exposure = 0.5 * (expected_exposure_neg[j] + expected_exposure_neg[j-1])

    df = base_discount_curve.discount(dates[j])
    dva += own_LGD * prob_own_default * avg_neg_exposure * df
  return dva

# FVA (hypothèse portefeuille non collatéralisé, donc pas de calcul du MVA)

# 100 bps, spread de financement de notre banque par défaut
def compute_fva(times, dates, expected_exposure, base_discount_curve, end_date=None, funding_spread=0.01):
  fva = 0.0
  for j in range(1, len(times)):
    if dates[j] > end_date:
      break
    dt = times[j] - times[j-1]
    df = base_discount_curve.discount(dates[j])
    avg_exposure = 0.5 * (expected_exposure[j] + expected_exposure[j-1])
    fva += funding_spread * avg_exposure * df * dt
  return fva

# KVA

# RW pondération réglementaire (risk weight), CR ratio de capital réglementaire (exigence minimale de Bâle III) et coût du capital (rendement exigé par les actionnaires autour de 8–12%) par défaut
def compute_kva(times, dates, expected_exposure, base_discount_curve, end_date=None, RW=1.0, CR=0.08, cost_of_capital=0.10):
  kva = 0.0
  for j in range(1, len(times)):
    if dates[j] > end_date:
      break
    dt = times[j] - times[j-1]
    df = base_discount_curve.discount(dates[j])
    avg_exposure = 0.5 * (expected_exposure[j] + expected_exposure[j-1])
    capital_t = RW * CR * avg_exposure # capital réglementaire requis
    kva += cost_of_capital * capital_t * df * dt
  return kva

for k, name in enumerate(product_names):
  cva = compute_cva(times, dates, ee_by_product[k], base_discount_curve, product_end_dates[k])
  dva = compute_dva(times, dates, ene_by_product[k], base_discount_curve, product_end_dates[k])
  fva = compute_fva(times, dates, ee_by_product[k], base_discount_curve, product_end_dates[k])
  kva = compute_kva(times, dates, ee_by_product[k], base_discount_curve, product_end_dates[k])

  print(f"CVA Totale {name} : {cva:,.2f} EUR")
  print(f"DVA {name} : {dva:,.2f} EUR")
  print(f"BCVA {name} (CVA - DVA) : {cva - dva:,.2f} EUR") # impact net des deux risques sur la valeur du swap
  print(f"FVA {name} : {fva:,.2f} EUR")
  print(f"KVA {name} : {kva:,.2f} EUR")
  print("----")

# check de cohérence : affichage de la moyenne des EE et ENE pour chaque produit sur les périodes actives
for k, name in enumerate(product_names):
  end_date = product_end_dates[k]
  active_idx = [j for j, d in enumerate(dates) if d <= end_date]

  ee_mean = np.mean(ee_by_product[k][active_idx])
  ene_mean = np.mean(ene_by_product[k][active_idx])

  print(f"{name}: EE moyen = {ee_mean:,.2f} EUR | ENE moyen = {ene_mean:,.2f} EUR")

# Pour chaque produits du portefeuille, valeur économique = valeur théorique - CVA + DVA - FVA - MVA - KVA

mva = 0.0  # contrats non-collatéralisés

for k, name in enumerate(product_names):
  theo = products[k].NPV()

  cva = compute_cva(times, dates, ee_by_product[k], base_discount_curve, product_end_dates[k])
  dva = compute_dva(times, dates, ene_by_product[k], base_discount_curve, product_end_dates[k])
  fva = compute_fva(times, dates, ee_by_product[k], base_discount_curve, product_end_dates[k])
  kva = compute_kva(times, dates, ee_by_product[k], base_discount_curve, product_end_dates[k])

  economic_value = theo - cva + dva - fva - mva - kva

  print(f"{name} — Valeur théorique : {theo:,.2f} EUR")
  print(f"{name} — Valeur économique : {economic_value:,.2f} EUR")
  print(f"(CVA {cva:,.2f} / DVA {dva:,.2f} / FVA {fva:,.2f} / MVA {mva:,.2f} / KVA {kva:,.2f})")
  print("----")

